export const SUCCESS_ITEMS = [
	{
		id: "success5",
		date: "18.11.2022",
		title: "18 XI 2022. Wspomnienie Bł. Karoliny Kózkówny, patronki naszego Przedszkola.",
		content1: "",
		signature: "",
		imagePath: "images/swieto_patronki2022",
		imgFolderLength: 56,
	},
	{
		id: "success4",
		date: "05.10.2022",
		title: "Baśnie Pana Andersena",
		content1: "W dniu 05.10.2022r w Brzesku, przedszkolaki uczestniczyli w spektaklu Baśnie Pana Andersena.",
		signature: "",
		imagePath: "images/basnieAndersena2022",
		imgFolderLength: 75,
	},
	{
		id: "success3",
		date: "28.08.2022",
		title: "Występ na Pikniku Parafialnym",
		content1: "",
		signature: "",
		imagePath: "images/wystepPiknik2022",
		imgFolderLength: 24,
	},
	{
		id: "success2",
		date: "2022",
		title: "Poświęcenie pokarmów - Publiczne Przedszkole Parafialne w Mokrzyskach pw. Błogosławionej Karoliny Kózka",
		content1: "",
		signature: "",
		imagePath: "images/wielkanoc2022",
		imgFolderLength: 15,
	},
	{
		id: "success1",
		date: "2021",
		title: "Pielgrzymowanie Przedszkolaków do św. Stanisława w Szczepanowie",
		content1: "",
		signature: "",
		imagePath: "images/szczepanow2021",
		imgFolderLength: 51,
	},
];
