export { default as AboutUs } from "./AboutUs";
export { default as BannerSlider } from "./BannerSlider";
export { default as Burger } from "./Burger";
export { default as Button } from "./Button";
export { default as Cadre } from "./Cadre";
export { default as Contact } from "./Contact";
export { default as Cookies } from "./Cookies";
export { default as Documents } from "./Documents";
export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as InfoViev } from "./Informations";
export { default as MainSwitch } from "./MainSwitch";
export { default as Maps } from "./Maps";
export { default as Menu } from "./Menu";
export { default as Modal } from "./Modal";
export { NewsItem, NewsViev } from "./News";
export { default as Patroness } from "./Patroness";
export { default as Spinner } from "./Spinner";
export { default as StartViev } from "./StartViev";
export { Success, SuccessItem } from "./Success";
export { default as SuccessPicViev } from "./SuccecPicViev";
export { default as TopArrow } from "./TopArrow";
